#inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Naming/FileName:
  Exclude:
    - lib/omniauth-indieauth.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    IndieAuth: indieauth
    OmniAuth: omniauth
